### ISSUE TITLE
Add Password Strength Feature

### ISSUE THREAD

**Issue by phenyloder** [2024-SANDHYA/Blood-Buddy#34] opened 2021-12-03 06:51 UTC
On the Register Page, when a password is entered, the slider below is static and does not shows the password strength.

I would like to implement the password Strength Check feature using JavaScript and so the bar below will show red if the password is weak, yellow for an average one and green for the Strong Passwords.

Please assign this to me.

**Comment by 2024-SANDHYA** [comment] 2021-12-03 07:24
> On the Register Page, when a password is entered, the slider below is static and does not shows the password strength.
> 
> I would like to implement the password Strength Check feature using JavaScript and so the bar below will show red if the password is weak, yellow for an average one and green for the Strong Passwords.
> 
> Please assign this to me.

Sure go ahead !! @phenyloder

**Comment by leesha19** [comment] 2021-12-03 09:53
i have already mentioned this issue how can you assign it to someone else @2024-SANDHYA

**Comment by leesha19** [comment] 2021-12-03 09:59
> > On the Register Page, when a password is entered, the slider below is static and does not shows the password strength.
> > I would like to implement the password Strength Check feature using JavaScript and so the bar below will show red if the password is weak, yellow for an average one and green for the Strong Passwords.
> > Please assign this to me.
> 
> Sure go ahead !! @phenyloder

i have earlier mentioned the same issue but i think you deleted that issue

**Comment by 2024-SANDHYA** [comment] 2021-12-03 10:13
> > > On the Register Page, when a password is entered, the slider below is static and does not shows the password strength.
> > > I would like to implement the password Strength Check feature using JavaScript and so the bar below will show red if the password is weak, yellow for an average one and green for the Strong Passwords.
> > > Please assign this to me.
> > 
> > 
> > Sure go ahead !! @phenyloder
> 
> i have earlier mentioned the same issue but i think you deleted that issue

The issue is still there before arriving at any conclusion please check #32  @leesha19

**Comment by phenyloder** [comment] 2021-12-03 11:40
Ma'am, I've made the PR. Hence it's my request to kindly review it and do tell if you find something missing. I would definitely try to improve it. 

Thank You.

**Closed** 2021-12-17 12:18 UTC
Labels: enhancement, good first issue, SWOC'21, MEDIUM
